title: My GH Pages Title
author: markphip
email: markphip@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  This is just my testing of GH pages and static site generation

# social links
twitter_username: markphip # DO NOT include the @ character, or else the build will fail!
github_username:  markphip # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
